#pragma config(Motor,  port1,           Left,          tmotorNormal, openLoop)
#pragma config(Motor,  port2,           BackR,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           BackL,         tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Right,         tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/******************************\
|    5 second Delay for VEX    |
|     By: Konrad Kraemer       |
|           9/8/11             |
|                              |
|   Makes the VEX run          |
|   Commands with a 5 second   |
|   Delay                      |
|                              |
\******************************/

task main(){
  int i = 0;
    int controlR[500];
    int controlL[500];
    while(i<500)
    {
        controlR[i] = vexRT[Ch2];
        controlL[i] = vexRT[Ch3];
        i = i + 1 ;
    }
    i = 0;
    int x = 0;
    while(x != 180){
        motor[Right] = controlR[i];
        motor[BackR] = controlR[i];
        motor[Left] = controlL[i];
        motor[BackL] = controlL[i];
        controlR[i] = vexRT[Ch2];
        controlL[i] = vexRT[Ch3];
        if(i<499){
            i = i + 1 ;
        } else {
            i = 0;
        }
        x = vexRT[Ch5];
    }
}
