#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armL,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  armR,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftBelt,      tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           arm4,          tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           arm,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           arm3,          tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           rightBelt,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop, reversed)
#pragma DebuggerWindows ("JoystickSimple")
#include "JoystickDriver.c"
*/


task main() {
	while (1) {
		if(vexRT(Btn8U)) {
			motor[rightFront] = 127;
			motor[rightBack] = 127;
			motor[leftBack] = 127;
			motor[leftFront] = 127;
		} else {
			motor[rightFront] = 0;
			motor[rightBack] = 0;
			motor[leftBack] = 0;
			motor[leftFront] = 0;
		}
	}
}
