#pragma config(Motor,  port1,           left,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          right,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  while(true){
    motor[left] = vexRT[Ch3];
    motor[right] = vexRT[Ch2];
    //tis wierd
    //oh noes!!!!
  }
}
