#pragma config(Motor,  port1,           fwdL,          tmotorNormal, openLoop)
#pragma config(Motor,  port2,           fwdR,          tmotorNormal, openLoop)
#pragma config(Motor,  port3,           bckL,          tmotorNormal, openLoop)
#pragma config(Motor,  port4,           bckR,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main (){
  int x = 0;
  while(x==0){
    int m1, m2, m3, m4;
    m1 = vexRT[Ch3];
    m2 = vexRT[Ch3];
    m3 = vexRT[Ch3];
    m4 = vexRT[Ch3];
    m1 = m1 + vexRT[Ch4];
    m2 = m2 - vexRT[Ch4];
    m3 = m3 - vexRT[Ch4];
    m4 = m4 + vexRT[Ch4];
    if(vexRT[Btn8R] == 1 && vexRT[Btn8L] == 0){
    m1 = m1 + 64;
    m2 = m2 - 64;
    m3 = m3 + 64;
    m4 = m4 - 64;
    } else if(vexRT[Btn8L] == 1 && vexRT[Btn8R] == 0){
    m1 = m1 - 64;
    m2 = m2 + 64;
    m3 = m3 - 64;
    m4 = m4 + 64;
    }
    if(m1 > 127){
      m1 = 127;
    } else if(m1 < -127){
      m1 = -127;
    }
    if(m2 > 127){
      m2 = 127;
    } else if(m2 < -127){
      m2 = -127;
    }
    if(m3 > 127){
      m3 = 127;
    } else if(m3 < -127){
      m3 = -127;
    }
    if(m4 > 127){
      m4 = 127;
    } else if(m4 < -127){
      m4 = -127;
    }
    motor[fwdL] = m1;
    motor[fwdR] = m2;
    motor[bckL] = m3;
    motor[bckR] = m4;

    if(vexRT[Btn7U] == 1){
      x = 1;
    }
  }

}
