#pragma config(Motor,  port1,           Right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           Left,          tmotorNormal, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorNormal, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  bool active = true;
  while(active == true){
    int mL, mR;
    mL = vexRT[Ch3];
    mR = vexRT[Ch3];
    mL = mL + vexRT[Ch4];
    mR = mR - vexRT[Ch4];
    if(mL > 127){
      mL = 127;
    } else if(mL < -127){
      mL = -127;
    }
    if(mR > 127){
      mR = 127;
    } else if(mR < -127){
      mR = -127;
    }
    motor[arm] = (vexRT[Btn5U] * 127) - (vexRT[Btn5D] * 127);
    motor[claw] = motor[claw] + (vexRT[Btn6U] * 5) - (vexRT[Btn6D] * 5);
    motor[Left] = mL;
    motor[Right] = mR;


    if(vexRT[Btn8R] == 1){
      active = false;
    }
  }
}
