#pragma config(Motor,  port1,           Left,          tmotorVex269, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//=====================================================================================================================
//											DEFINE
//=====================================================================================================================
//     1 = omni

void move (int rotations, int speed);
void moveThenStop (int rotations, int speed);
void moveThenGlide (int rotations, int speed);
void mstop();
void glide();
void RC();



task main() {
  bool end = false;
  //robot rbt
  while (end == false) {
    RC();
  }
}

void move (int rotations, int speed) {
  motor[Left] = speed;
  motor[Right] = speed;
  wait1Msec(rotations * 600);
}

void mstop() {
  motor[Left] = -1;
  motor[Right] = -1;
  motor[Left] = 0;
  motor[Right] = 0;
}

void glide() {
  bool end = false;
  while (end == false){
    if (motor[Left] > 0){
      motor[Left] = motor[Left] - 1;
    }
    if (motor[Right] > 0){
      motor[Right] = motor[Right] - 1;
    }
    if (motor[Left] < 0){
      motor[Left] = motor[Left] + 1;
    }
    if (motor[Right] > 0){
      motor[Right] = motor[Right] + 1;
    }
    if (motor[Right] == 0 && motor[Left] == 0){
      end = true;
    } else {
      wait10Msec(1);
    }
  }
}

void moveThenStop (int rotations, int speed) {
  move(rotations, speed);
  mstop();
}

void moveThenGlide (int rotations, int speed) {
  move(rotations, speed);
  glide();
}

void RC(){
  bool active = true;
  while(active == true){
    int mL, mR;
    mL = vexRT[Ch3];
    mR = vexRT[Ch3];
    mL = mL + vexRT[Ch4];
    mR = mR - vexRT[Ch4];
    if(mL > 127){
      mL = 127;
    } else if(mL < -127){
      mL = -127;
    }
    if(mR > 127){
      mR = 127;
    } else if(mR < -127){
      mR = -127;
    }
    motor[Left] = mL;
    motor[Right] = mR;


    if(vexRT[Btn7U] == 1){
      active = false;
    }
  }
}
