#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows ("JoystickSimple")

#include "JoystickDriver.c"

task main() {
	double EL = 0.9764829765;
	double ER = 1;
	int mL = 0;
	int mR = 0;
	nMotorEncoder[frontLeftMotor] = 0;
	nMotorEncoder[frontRightMotor] = 0;
	while(true){
		getJoystickSettings(joystick);
		mL = 0;
		mR = 0;
		if(joy1Btn(1) == 0 && joy1Btn(2) == 0 && joy1Btn(3) == 0 && joy1Btn(4) == 1){
			mL = 70 * EL ; mR = 70 * ER;
		}

	motor[frontLeftMotor] = 1.05 * mL;
	motor[rearLeftMotor] = 1.05 * mL;
	motor[frontRightMotor] = mR;
	motor[rearRightMotor] = mR;
	}
}

//1 back 2 right 3 left
