#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows ("JoystickSimple")

#include "JoystickDriver.c"

task main() {
	int mL = 0;
	int mR = 0;
	int diff = 0;
	int EL = 1;
	int ER = 1;
	int dir = 0;
	nMotorEncoder[frontLeftMotor] = 0;
	nMotorEncoder[frontRightMotor] = 0;
	while(true){
		getJoystickSettings(joystick);
		mL = 0;
		mR = 0;
		if(joy1Btn(1) == 0 && joy1Btn(2) == 0 && joy1Btn(3) == 0 && joy1Btn(4) == 1){
			if (dir != 4) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 4;
			}
			mL = 70; mR = 70;
			diff = EL * nMotorEncoder[frontLeftMotor] - (ER * nMotorEncoder[frontRightMotor]);
			if (diff > 0 ){
				mL -= diff * 10;
			} else if (diff < 0){
				mR += diff * 10;
			}
		}
		if(joy1Btn(1) == 1 && joy1Btn(2) == 0 && joy1Btn(3) == 0 && joy1Btn(4) == 0){
			if (dir != 1) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 1;
			}
			mL = -70; mR = -70;
			diff = EL * nMotorEncoder[frontLeftMotor] - (ER * nMotorEncoder[frontRightMotor]);
			if (diff > 0 ){
				mR += diff * 10;
			} else if (diff < 0){
				mL -= diff * 10;
			}
		}
		if(joy1Btn(1) == 0 && joy1Btn(2) == 1 && joy1Btn(3) == 0 && joy1Btn(4) == 0){
			if (dir != 2) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 2;
			}
			mL = 70; mR = -70;
			diff = EL * nMotorEncoder[frontLeftMotor] + (ER * nMotorEncoder[frontRightMotor]);
			if (diff > 0 ){
				mL -= diff * 10;
			} else if (diff < 0){
				mR -= diff * 10;
			}
		}
		if(joy1Btn(1) == 0 && joy1Btn(2) == 0 && joy1Btn(3) == 1 && joy1Btn(4) == 0){
			if (dir != 3) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 3;
			}
			mL = -70; mR = 70;
			diff = EL * nMotorEncoder[frontLeftMotor] + (ER * nMotorEncoder[frontRightMotor]);
			if (diff > 0 ){
				mR -= diff * 10;
			} else if (diff < 0){
				mL -= diff * 10;
			}
		}

	motor[frontLeftMotor] = 1.05 * mL;
	motor[rearLeftMotor] = 1.05 * mL;
	motor[frontRightMotor] = mR;
	motor[rearRightMotor] = mR;
	}
}

//1 back 2 right 3 left
