#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rearLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           frontRightMotor, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port10,          rearRightMotor, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lMotor = 0;
int rMotor = 0;
int diff = 0;
task main() {
	int mL = 0;
	int mR = 0;
	float EL = .7;
	float ER = 1;
	int dir = 0;
	nMotorEncoder[frontLeftMotor] = 0;
	nMotorEncoder[frontRightMotor] = 0;
	while(true){
		mL = 0;
		mR = 0;
		if(vexRT[Btn8U]){
			if (dir != 4) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 4;
			}
			lMotor = nMotorEncoder[frontLeftMotor];
			rMotor = nMotorEncoder[frontRightMotor];
			mL = 70; mR = 70;
			//diff = nMotorEncoder[frontLeftMotor] - nMotorEncoder[frontRightMotor];
			if (diff > 0 ){
				mL -= diff * 2;
			} else if (diff < 0){
				mR += diff * 2;
			}
		}
		if(vexRT[Btn8D]){
			if (dir != 1) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 1;
			}
			mL = -70; mR = -70;
			diff = nMotorEncoder[frontLeftMotor] - nMotorEncoder[frontRightMotor];
			if (diff > 0 ){
				mR += diff * 2;
			} else if (diff < 0){
				mL -= diff * 2;
			}
		}
		if(vexRT[Btn8R]){
			if (dir != 2) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 2;
			}
			mL = 70; mR = -70;
			diff = nMotorEncoder[frontLeftMotor] + nMotorEncoder[frontRightMotor];
			if (diff > 0 ){
				mL -= diff * 2;
			} else if (diff < 0){
				mR -= diff * 2;
			}
		}
		if(vexRT[Btn8L]){
			if (dir != 3) {
				nMotorEncoder[frontLeftMotor] = 0;
				nMotorEncoder[frontRightMotor] = 0;
				dir = 3;
			}
			mL = -70; mR = 70;
			diff = nMotorEncoder[frontLeftMotor] + nMotorEncoder[frontRightMotor];
			if (diff > 0 ){
				mR -= diff * 2;
			} else if (diff < 0){
				mL -= diff * 2;
			}
		}

	motor[frontLeftMotor] = mL * EL;
	motor[rearLeftMotor] = mL * EL;
	motor[frontRightMotor] = mR * ER;
	motor[rearRightMotor] = mR * ER;
	}
}
