#pragma config(Motor,  port1,           L1,            tmotorNormal, openLoop)
#pragma config(Motor,  port2,           R1,            tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           L2,            tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           R2,            tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move (int rotations, int speed) {
  motor[R1] = speed * (rotations / abs( rotations) );
  motor[L1] = speed * (rotations / abs( rotations) );
  motor[R2] = speed * (rotations / abs( rotations) );
  motor[L2] = speed * (rotations / abs( rotations) );
  wait1Msec((abs(rotations) * 600) * (127 / speed));
}

void brake () {
  motor[R1] = 0 ;
  motor[L1] = 0 ;
  motor[R2] = 0 ;
  motor[L2] = 0 ;
}

task main() {
 bool rc = true;
 while (rc == true) {
  motor[L1] = vexRT[Ch3] ;
  motor[R1] = vexRT[Ch2] ;
  motor[L2] = vexRT[Ch3] ;
  motor[R2] = vexRT[Ch2] ;

  if (vexRT[Btn8U] == 1)
    rc = false;
}
  move(5, 63);
  move(2, 24);
  move(-7, 127);
  brake();
}
