#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armL,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  armR,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftBelt,      tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           arm,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           arm3,          tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port8,           arm4,          tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightBelt,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float EL = .7;
float ER = 1;

#include "Autonomous.c"
#include "RC1.h"

//rotation sensor = 627.2 counts per rotation. Konrad is awesome at coding. The lady bangers will win it all. Noah is a floating ass. Carson is a sophomore. that means he's stupid :).

task main() {
	Autonomous();
	RCcontroller();
}
