#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    leftScissorRot, sensorPotentiometer)
#pragma config(Sensor, in3,    rightScissorRot,sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port2,           leftBack,      tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           rightScissor1, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           rightScissor2, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           leftScissor1,  tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftScissor2,  tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftBelt,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightBelt,     tmotorVex393, openLoop, encoder, encoderPort, I2C_5, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop, reversed)
#pragma DebuggerWindows ("JoystickSimple")
#include "JoystickDriver.c"
*/


/*****************************************************\
|   Code by Konrad Kraemer                            |
|                                                     |
|   Current Version 3.0                               |
|                                                     |
|   Modular code to ease testing on VirtualWorlds.    |
|   Autonomous code records itself using the          |
|   writeStream() function.                           |
|                                                     |
|                                                     |
| 3.0   Rewrite - codebase completely rewritten to    |
|           acommodate the mechanum wheels, control   |
|           the scissor lift, and redo the autonomous |
|           to run from a library, instead of the     |
|           recording done in previous years. Also,   |
|           remote control code was modified to allow |
|           the controls to always be in-relation to  |
|           driver, regardless of the rotation of the |
|           robot.                                    |
|                                                     |
| 2.0.8.1 Tweak- correction value changed to .5 to    |
|           make the autonomous even less jumpy       |
|                                                     |
| 2.0.8 Modification- removed the lurching and        |
|           anti-tippingcode because our drivers      |
|           thought it limited our mobility           |
|                                                     |
| 2.0.7 Feature Replacement- we decided that we need  |
|           full power, so we are dropping the 2.0.5  |
|           changes, and instead tweaking the accel   |
|                                                     |
| 2.0.6	Feature- software speed limiting to prevent   |
|           the robot from lurching forward if arm    |
|           is fully up. This previously caused the   |
|           robot to flip.                            |
|                                                     |
| 2.0.5	Feature- software arm limiting to prevent the |
|           arm from exceding a certain height and    |
|           flipping the robot. Also, this code turns |
|           off the automatic arm power which would   |
|           keep it level.                            |
|                                                     |
| 2.0.4.1 Tweak- ticks to give up changed to 500      |
|           ticks. Now it doesn't take soo long       |
|           to move on. Also, correction value        |
|           changed to 1 to make it less jumpy.       |
|                                                     |
| 2.0.4	BugFix- told robot to give up after           |
|           1000 ticks. Robot used to try to          |
|           complete a command indefinitely, if       |
|           it hit a wall, it would just sit there    |
|           and do nuthin, so now it gives up.        |
|                                                     |
| 2.0.3.2 Tweak- deadzone changed to 27.              |
|           Maximum speed becomes 100                 |
|           JANUARY 6, 2014                           |
|                                                     |
| 2.0.3.1 Bugfix- correction code wasn't working.     |
|           motor values went to -3000s. Problem was  |
|           that I accidentaly read the left encoder  |
|           instead of the right encoder              |
|           JANUARY 6, 2014                           |
|                                                     |
| 2.0.3	Bugfix- some motors were having problems      |
|           catching up with the others, added code   |
|           to set the max speed for motors during    |
|           recording to 127 MINUS the value of       |
|           variable deadzone (max 122).              |
|           JANUARY 6, 2014                           |
|                                                     |
| 2.0.2	Bugfix- same problem as 2.0.1, I solved it    |
|           by having the code wait until any encoder |
|           reaches its predefined target for that    |
|           cycle.     JANUARY 5, 2014                |
|                                                     |
| 2.0.1 Bugfix- since the recording code takes more   |
|           time to execute than the autonomous, the  |
|           autonomous code ends up running a tad too |
|           quickly. I started fixing this by forcing |
|           certain parts of the code to execute at   |
|           a certain time, however I abandoned this  |
|           approach and went with another (2.0.2)    |
|           JANUARY 4, 2014                           |
|                                                     |
| 2.0  Complete rewrite- modular code to aid          |
|           testing in VirtualWorlds and make it      |
|           more legible. Autonoumous recording now   |
|           supports full control with thumbsticks    |
|           December 28, 2013                         |
|                                                     |
| 1.2 Rewrote Autonomous- Working - FALL 2013         |
|           Codes itself, uses D-pad controls         |
|           (fwd,back,turnLeft,turnRight)             |
|                                                     |
| 1.1 Added self-writing Autonomous                   |
|           Was not functional, witten early 2013     |
|                                                     |
| 1.0 Original Version Of remote code - Late 2012     |
|                                                     |
|                                                     |
\*****************************************************/

//=====================
//includes
//=====================
#include "Vars.h" // file for global vars
#include "Writer.h" // file which has code for recording inputs and outputting autonomous code
#include "calculateMotors.h"

//#include "RobotVirtual.h" //when testing with virtual worlds
//#include "RCVirtual.h"
#include "Robot.h"  //when using actual robot
#include "RC.h"

#include "autoControl.h"
#include "autoCode.h"

//#include "Autonomous.h" // main autonomous file, includes more files

//rotation sensor = 627.2 counts per rotation. Konrad is awesome at coding. The lady bangers will win it all. Noah is a floating ass. Carson is a sophomore. that means he's stupid :).



task main() {
	resetVars(); // reset all variables
	resetSensors(); // reset all sensors
	AutoRF();//run the RedFront autonomous
	while (true) {
		RC();  // recieve inputs
		calcMotorValues();
		writeStream();
		RunRobot();
	}
}
