#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armL,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  armR,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftBelt,      tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           arm4,          tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           arm,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           arm3,          tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           rightBelt,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//writeDebugStreamLine("int x is: %d", x);

int lMotor = 0;
int rMotor = 0;
int aMotorR = 0;
int aMotorL = 0;
int diff = 0;
int dir = 0;
bool armImpDown = false;

void stream();

task main() {
	int mL = 0;
	int mR = 0;
	float EL = .9764829765;
	float ER = 1;
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[rightFront] = 0;
	nMotorEncoder[arm2] = 0;
	nMotorEncoder[arm3] = 0;
	while(true){
		mL = 0;
		mR = 0;
		if(vexRT[Btn8U]){
			if (dir != 4) {
				stream();
				nMotorEncoder[leftFront] = 0;
				nMotorEncoder[rightFront] = 0;
				dir = 4;
			}
			lMotor = nMotorEncoder[leftFront];
			rMotor = nMotorEncoder[rightFront];
			mL = 70; mR = 70;
			diff = nMotorEncoder[leftFront] - nMotorEncoder[rightFront];
			if (diff > 0 ){
				mL -= diff * 2;
			} else if (diff < 0){
				mR += diff * 2;
			}
		}
		if(vexRT[Btn8D]){
			if (dir != 1) {
				stream();
				nMotorEncoder[leftFront] = 0;
				nMotorEncoder[rightFront] = 0;
				dir = 1;
			}
			mL = -70; mR = -70;
			diff = nMotorEncoder[leftFront] - nMotorEncoder[rightFront];
			if (diff > 0 ){
				mR += diff * 2;
			} else if (diff < 0){
				mL -= diff * 2;
			}
		}
		if(vexRT[Btn8R]){
			if (dir != 2) {
				stream();
				nMotorEncoder[leftFront] = 0;
				nMotorEncoder[rightFront] = 0;
				dir = 2;
			}
			mL = 70; mR = -70;
			diff = nMotorEncoder[leftFront] + nMotorEncoder[rightFront];
			if (diff > 0 ){
				mL -= diff * 2;
			} else if (diff < 0){
				mR -= diff * 2;
			}
		}
		if(vexRT[Btn8L]){
			if (dir != 3) {
				stream();
				nMotorEncoder[leftFront] = 0;
				nMotorEncoder[rightFront] = 0;
				dir = 3;
			}
			mL = -70; mR = 70;
			diff = nMotorEncoder[leftFront] + nMotorEncoder[rightFront];
			if (diff > 0 ){
				mR -= diff * 2;
			} else if (diff < 0){
				mL -= diff * 2;
			}
		}
		if(vexRT[Btn7U] && !armImpDown) {
			armImpDown = true;
			int x = nMotorEncoder[arm2];
			if (x > 0)
				writeDebugStreamLine("ArmUp(%d);", x);
			else
				writeDebugStreamLine("ArmDown(%d);", (-1 * x));
			nMotorEncoder[arm2] = 0;
			nMotorEncoder[arm3] = 0;
		}
		if(!vexRT[Btn7U])
			armImpDown = false;

	motor[leftFront] = mL * EL;
	motor[leftBack] = mL * EL;
	motor[rightFront] = mR * ER;
	motor[rightBack] = mR * ER;

	if(vexRT[Btn5U] || vexRT[Btn6U]) {
		motor[rightBelt] = 127;
		motor[leftBelt] = 127;
	}
	if(vexRT[Btn6D] || vexRT[Btn5D]) {
		motor[rightBelt] = -127;
		motor[leftBelt] = -127;
	}
	if(!vexRT[Btn5U] && !vexRT[Btn5D] && !vexRT[Btn6D] && !vexRT[Btn6U]) {
		motor[leftBelt] = 0;
		motor[rightBelt] = 0;
	}

	if(vexRT[Ch2] >= 10 || vexRT[Ch2] <= -10)
		motor[arm2] = vexRT[Ch2];
	else
		motor[arm2] = 10;
	//int diffA = nMotorEncoder[arm2] - nMotorEncoder[arm3];
	motor[arm3] = motor[arm2];// + diffA * 2;
	motor[arm] = motor[arm2];
	motor[arm4] = motor[arm3];

	aMotorL = nMotorEncoder[arm2];
	aMotorR = nMotorEncoder[arm3];
	}
}

void stream() {
	int x = nMotorEncoder[leftFront];
	if (dir == 4) {
		writeDebugStreamLine("moveForward(%d,70);", x);
	}
	if (dir == 1) {
		writeDebugStreamLine("moveBack(%d,70);", (-1* x));
	}
	if (dir == 2) {
		writeDebugStreamLine("turnRight(%d,70);", x);
	}
	if (dir == 3) {
		writeDebugStreamLine("turnLeft(%d,70);", (-1* x));
	}
}
